### PR TITLE
:sparkles: Add cronjon for `docker system prune`

### PR DESCRIPTION
**Pull request by baccenfutter**

### CODE REVIEW

**Review by holtgrewe — APPROVED** [review]
Can we also have a `docker_cron_system_prune_enabled` setting defaulting to `true`? If that's implemented please merge and tag. I will update the tag on ansible galaxy.

**Comment by baccenfutter** [comment]
https://github.com/bihealth/ansible-role-docker/blob/3cb088ddc37bad60417ee33ee13c6bab2ae7ebaf/tasks/main.yml#L42

Setting the variable `docker_cron_system_prune` to an empty dict or any other falsey value achieves exactly that without introducing another variable. Is that not even better?

**Comment by holtgrewe** [comment]
> https://github.com/bihealth/ansible-role-docker/blob/3cb088ddc37bad60417ee33ee13c6bab2ae7ebaf/tasks/main.yml#L42
> 
> Setting the variable `docker_cron_system_prune` to an empty dict or any other falsey value achieves exactly that without introducing another variable. Is that not even better?

Really? Can you first enable it, run the playbook, and then remove the cron job again? Of course you could copy and paste the entry from the source, adjust, ... That's not the same.

**Comment by baccenfutter** [comment]
Oh, well that's an entirely new feature as per issue definition. I can implement that either with an extra variable or with the same pattern as above.

**Comment by holtgrewe** [comment]
> Oh, well that's an entirely new feature as per issue definition. I can implement that either with an extra variable or with the same pattern as above.

Technically that is correct as the ticket definition then should write "Allow for adding and removing a cron job". Technically.

**Comment by baccenfutter** [comment]
Well, it's that and the fact that I can't think of any other place in our roles where we would have implemented a rollback via variable.

Anyways, it is pretty simple to implement in this case, but the question remains if I should feature this with two separate variables or a single variable?

**Comment by holtgrewe** [comment]
One variable for enabling/disabling one for configuration please.

**Comment by baccenfutter** [comment]
Looks like the builtin module already supports this out-of-the-box:
- https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html#parameter-disabled

Should I implement anyways?

**Comment by holtgrewe** [comment]
Yes please as this does not require us to locate the YAML snippet for adding the cron job in the defaults, copy it over to the config, adjust it to disable...

**Comment by baccenfutter** [comment]
> Looks like the builtin module already supports this out-of-the-box:
> 
>     * https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html#parameter-disabled
> 
> 
> Should I implement anyways?

Or perhaps change the defaults to:

```yaml
docker_cron_system_prune:
  name: remove unused images, volumes, containers, etc
  job: docker system prune -f
  hour: 0
  minute: 0
  user: root
  disabled: false   ## <- explicit is better than implicit and makes the feature more visible and obvoious
```

**Comment by holtgrewe** [comment]
What about?

```
docker_cron_system_prune_enabled: true
docker_cron_system_prune_config:
  name: remove unused images, volumes, containers, etc
  job: docker system prune -f
  hour: 0
  minute: 0
  user: root
  disabled: "{{ not docker_cron_system_prune_enabled }}"
```

**Comment by holtgrewe** [comment]
LGTM, please merge.

**Comment by holtgrewe** [comment]
(and tag)

**Pull request merged**
